name: Deploy Cloud Function (manual)

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy functions:scoreAndSave
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install firebase-tools
        run: |
          npm install -g firebase-tools@latest

      - name: Deploy Cloud Function
        run: |
          firebase deploy --only functions:scoreAndSave --project nemmadi-bbf77
